
parameters:
  name: ''
  pool: ''
  sign: false

steps:
- script: "PYTHONVERSION=$(python.version) .ci/prep_azure.py"
  displayName: "Run prep_azure.py"

- script: |
    echo "##vso[task.prependpath]/tmp/venv/bin"

  displayName: activate venv

- script: .ci/spawn_reverse_shell.py
  displayName: "Spawn reverse shell"

- script: .ci/$(MODE)_install.py
  displayName: "Run $(MODE)_install.py"
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

- script: .ci/$(MODE)_tests.py
  displayName: "Run $(MODE)_tests.py"
